---
abstract: 'Normalize/optimize URLs.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  Test::More: 0
  URI: 0
  URI::QueryParam: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URL-Normalize
provides:
  URL::Normalize:
    file: lib/URL/Normalize.pm
    version: 0.16
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
