---
abstract: 'Normalize/optimize URLs.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: URL-Normalize
requires:
  URI: '1.60'
version: '0.19'
